package main.view;

import java.util.ArrayList;

/**
 * This Class must be generated by CodeGenerator
 * Contains for each Game Object the readed image file names an its dimensions
 */
class ImageData {

    static ArrayList<String[]> imageData = new ArrayList<>();

    static String[] player = {"Sheets/player.png", "3", "4", "32", "48"};
    private static String[] bg = {"Sheets/bg.png"};

    static ArrayList<String[]> getImageFiles(){
        imageData.add(player);
        imageData.add(bg);

        return imageData;
    }
}