package main.view;

import java.util.ArrayList;

/**
 * This Class must be generated by GraphicsCodeGenerator
 */
public class ImageFiles {
    private static ArrayList<String[]> imageFiles = new ArrayList<>();

    private static String[] player = {"player.png", "512", "512", "96"};
    private static String[] bullets = {"bullets.png", "128", "128", "32"};
    private static String[] atk = {"atk.png", "128", "96", "32"};
    private static String[] def = {"def.png", "512", "512", "96"};
    private static String[] bg = {"Sheets/bg.png"};

    public static ArrayList<String[]> getImageFiles(){
        imageFiles.add(player);
        imageFiles.add(bullets);
        imageFiles.add(atk);
        imageFiles.add(def);
        imageFiles.add(bg);

        return imageFiles;
    }
}
