package main.gui;

/**
 * Created by Pi on 14.06.2016.
 * This Class must be generated by GraphicsCodeGenerator
 */
public class ImageFiles {
    private String[] imageFiles = {
            "player.png, 512, 512, 96",
            "bullets.png, 128, 128, 32",
            "atk.png, 512, 512, 96",
            "def.png, 512, 512, 96",
            "bg.png, 128, 128, 128"
    };
    public String[] getImageFiles(){return imageFiles;}
}
